### ISSUE TITLE
Gracefully deal with unavailable target files

### ISSUE THREAD

**Issue by holtkamp** [dpovshed/octopus#38]
[`fopen()`](https://github.com/dpovshed/octopus/blob/985efd0867108519e0b377beb5464143d630bd9b/src/Processor.php#L183) returns `false` in case of failure, causing an error like:

```
First parameter must be a valid stream resource: 
#0 /app/vendor/octopoda/octopus/src/Processor.php(184): React\Stream\ReadableResourceStream->__construct(false, Object(React\EventLoop\StreamSelectLoop)) 
#1 /app/vendor/octopoda/octopus/src/Processor.php(177): Octopus\Processor->getStream() 
#2 /app/vendor/octopoda/octopus/src/Processor.php(127): Octopus\Processor->getTargetManager() 
#3 /app/MyCommand.php: Octopus\Processor->__construct(Object(Octopus\Config),
```

It would be nice to be able to deal with this situation.

**Comment by holtkamp** [comment]
Resolved with https://github.com/dpovshed/octopus/pull/39
Tagged in https://github.com/dpovshed/octopus/releases/tag/0.5.3
